apiVersion: v1
kind: Secret
metadata:
  name: thinkify-secret
  namespace: thinkify
type: Opaque
stringData:
  JWT_SECRET_KEY: "thinkify_super_secret_jwt_key_2024"
  DATABASE_URL: "mongodb://mongodb:27017/"
